CREATE TABLE IF NOT EXISTS booking_rules (
    id BIGINT PRIMARY KEY CHECK (id = 1),
    minimum_duration_minutes INTEGER NOT NULL DEFAULT 15 CHECK (minimum_duration_minutes > 0),
    maximum_duration_minutes INTEGER NOT NULL DEFAULT 1440 CHECK (maximum_duration_minutes >= minimum_duration_minutes),
    advance_booking_days INTEGER NOT NULL DEFAULT 90 CHECK (advance_booking_days >= 0),
    cancellation_deadline_minutes INTEGER NOT NULL DEFAULT 0 CHECK (cancellation_deadline_minutes >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT REFERENCES users(id)
);
INSERT INTO booking_rules(id) VALUES (1) ON CONFLICT (id) DO NOTHING;
CREATE TABLE IF NOT EXISTS bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id BIGINT NOT NULL REFERENCES resources(id),
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    start_at_utc TIMESTAMPTZ NOT NULL,
    end_at_utc TIMESTAMPTZ NOT NULL,
    purpose TEXT NOT NULL,
    project_reference TEXT,
    destination TEXT,
    status TEXT NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed','cancelled','completed')),
    created_by BIGINT NOT NULL REFERENCES users(id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cancelled_at TIMESTAMPTZ,
    cancellation_reason TEXT,
    CHECK (start_at_utc < end_at_utc),
    CHECK ((status = 'cancelled' AND cancelled_at IS NOT NULL) OR (status <> 'cancelled'))
);
CREATE INDEX IF NOT EXISTS idx_bookings_resource_time ON bookings(resource_id, start_at_utc, end_at_utc, status);
CREATE INDEX IF NOT EXISTS idx_bookings_owner ON bookings(owner_user_id, status, start_at_utc);
ALTER TABLE bookings DROP CONSTRAINT IF EXISTS bookings_no_confirmed_overlap;
ALTER TABLE bookings ADD CONSTRAINT bookings_no_confirmed_overlap
    EXCLUDE USING gist (resource_id WITH =, tstzrange(start_at_utc, end_at_utc, '[)') WITH &&)
    WHERE (status = 'confirmed');
